Repository Netflix/genie, pull requests merged in 2018-03, with the labels that each got.

#702 Upgrade to Spring State Machine 2.0.0.RELEASE
  build.gradle
Labels: Improvement

#704 Adding missing command executable to command args sent back with job specification
  genie-web/src/main/java/com/netflix/genie/web/services/impl/JobSpecificationServiceImpl.java
  genie-web/src/test/groovy/com/netflix/genie/web/services/impl/JobSpecificationServiceImplSpec.groovy
Labels: bug

#706 Move to Cairo RC1 and remove temporary library pins
  build.gradle
  gradle.properties
Labels: Improvement

#708 Removing deleteGenerateSources as dependency of java compile
  build.gradle
Labels: Improvement, bug

#709 Add adapters to convert v3 DTO to v4 DTO and vice versa at V3 API tier
  genie-common/src/main/java/com/netflix/genie/common/dto/v4/ClusterRequest.java
  genie-web/src/main/java/com/netflix/genie/web/controllers/DtoAdapters.java
  genie-web/src/test/groovy/com/netflix/genie/web/controllers/DtoAdaptersSpec.groovy
Labels: feature

#710 Export the job tags into runtime environment
  genie-core/src/main/java/com/netflix/genie/core/jobs/JobConstants.java
  genie-core/src/main/java/com/netflix/genie/core/jobs/workflow/impl/InitialSetupTask.java
  genie-core/src/test/java/com/netflix/genie/core/jobs/workflow/impl/InitialSetupTaskUnitTest.java
  genie-web/src/test/java/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests.java
  genie-web/src/test/resources/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests/linux-runsh.txt
  genie-web/src/test/resources/com/netflix/genie/web/controllers/JobRestControllerIntegrationTests/non-linux-runsh.txt
Labels: feature

#714 Upgrade to Spring Cloud Finchley M9
  gradle.properties
Labels: Improvement

#715 Expose job tags in job runtime environment
  genie-common/src/main/java/com/netflix/genie/common/jobs/JobConstants.java
  genie-web/src/main/java/com/netflix/genie/web/services/impl/JobSpecificationServiceImpl.java
  genie-web/src/test/groovy/com/netflix/genie/web/services/impl/JobSpecificationServiceImplSpec.groovy
Labels: feature
