Repository Netflix/genie, pull requests merged in 2019-01, with the labels that each got.

#815 User limit fast property (3.3.x)
  genie-core/src/main/java/com/netflix/genie/core/properties/JobsProperties.java
Labels: bug

#818 add columns wrap(main page)
  _layouts/frontpage.html
Labels: Improvement, documentation

#823 Upgrade various Gradle Plugins to their latest versions
  build.gradle
Labels: Improvement

#824 Add stacktrace as default argument for gradle on Travis builds
  travis/buildViaTravis.sh
Labels: Improvement
