Repository Netflix/genie, pull requests merged in 2020-12, with the labels that each got.

#1059 Upgrade Gradle to 6.7.1
  build.gradle
  genie-ui/npm-shrinkwrap.json
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#1061 Upgrade to Spock 2.0-M4
  build.gradle
  genie-agent/src/test/groovy/com/netflix/genie/agent/cli/AgentLogManagerSpec.groovy
  genie-agent/src/test/groovy/com/netflix/genie/agent/cli/JobRequestArgumentsImplSpec.groovy
  genie-agent/src/test/groovy/com/netflix/genie/agent/cli/ResolveJobSpecCommandSpec.groovy
  genie-agent/src/test/groovy/com/netflix/genie/agent/cli/logging/ConsoleLogSpec.groovy
  genie-agent/src/test/groovy/com/netflix/genie/agent/execution/process/impl/JobProcessManagerImplSpec.groovy
  genie-agent/src/test/groovy/com/netflix/genie/agent/execution/services/impl/DownloadServiceImplSpec.groovy
  genie-agent/src/test/groovy/com/netflix/genie/agent/execution/services/impl/FetchingCacheServiceImplSpec.groovy
  genie-agent/src/test/groovy/com/netflix/genie/agent/execution/services/impl/JobSetupServiceImplSpec.groovy
  genie-agent/src/test/groovy/com/netflix/genie/agent/execution/services/impl/grpc/GRpcAgentFileStreamServiceImplSpec.groovy
  genie-agent/src/test/groovy/com/netflix/genie/agent/execution/statemachine/stages/RelocateLogFileStageSpec.groovy
  genie-agent/src/test/groovy/com/netflix/genie/agent/utils/locks/impl/FileLockSpec.groovy
  genie-common-internal/src/test/groovy/com/netflix/genie/common/internal/dtos/DirectoryManifestSpec.groovy
  genie-common-internal/src/test/groovy/com/netflix/genie/common/internal/services/impl/FileSystemJobArchiverImplSpec.groovy
  genie-common-internal/src/test/groovy/com/netflix/genie/common/internal/services/impl/JobArchiveServiceImplSpec.groovy
  genie-common-internal/src/test/groovy/com/netflix/genie/common/internal/services/impl/S3JobArchiverImplSpec.groovy
  genie-web/src/test/groovy/com/netflix/genie/web/agent/inspectors/impl/WhitelistedVersionAgentMetadataInspectorSpec.groovy
  genie-web/src/test/groovy/com/netflix/genie/web/services/impl/LocalFileSystemAttachmentServiceImplSpec.groovy
Labels: Improvement, dependencies

#1062 Configurable memory overhead for Titus launcher
  genie-docs/src/docs/asciidoc/_properties.adoc
  genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImpl.java
  genie-web/src/main/java/com/netflix/genie/web/properties/TitusAgentLauncherProperties.java
  genie-web/src/test/groovy/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImplSpec.groovy
  genie-web/src/test/groovy/com/netflix/genie/web/properties/TitusAgentLauncherPropertiesSpec.groovy
Labels: Improvement

#1063 Templatize server hostname endpoint of local agent launcher
  genie-docs/src/docs/asciidoc/_properties.adoc
  genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/LocalAgentLauncherImpl.java
  genie-web/src/main/java/com/netflix/genie/web/properties/LocalAgentLauncherProperties.java
  genie-web/src/test/groovy/com/netflix/genie/web/agent/launchers/impl/LocalAgentLauncherImplSpec.groovy
  genie-web/src/test/groovy/com/netflix/genie/web/properties/LocalAgentLauncherPropertiesSpec.groovy
Labels: Improvement

#1064 Refactor Titus launcher properties related to resources
  genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImpl.java
  genie-web/src/main/java/com/netflix/genie/web/properties/TitusAgentLauncherProperties.java
  genie-web/src/test/groovy/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImplSpec.groovy
  genie-web/src/test/groovy/com/netflix/genie/web/properties/TitusAgentLauncherPropertiesSpec.groovy
Labels: Improvement
