Repository Netflix/genie, pull requests merged in 2020-07, with the labels that each got.

#1023 Fix Demo documentation script paths
  genie-demo/src/docs/asciidoc/index.adoc
Labels: documentation

#1024 Fix missing updates to job archive status
  genie-common-external/src/main/java/com/netflix/genie/common/external/dtos/v4/ArchiveStatus.java
  genie-web/src/main/java/com/netflix/genie/web/services/impl/JobCoordinatorServiceImpl.java
  genie-web/src/main/java/com/netflix/genie/web/services/impl/JobLaunchServiceImpl.java
  genie-web/src/test/groovy/com/netflix/genie/web/services/impl/JobLaunchServiceImplSpec.groovy
  genie-web/src/test/java/com/netflix/genie/web/services/impl/JobCoordinatorServiceImplTest.java
Labels: bug

#1025 Update controller and DirectoryServer service to use new archive status
  genie-docs/src/docs/asciidoc/_metrics.adoc
  genie-web/src/main/java/com/netflix/genie/web/apis/rest/v3/controllers/JobRestController.java
  genie-web/src/main/java/com/netflix/genie/web/services/impl/JobDirectoryServerServiceImpl.java
  genie-web/src/test/groovy/com/netflix/genie/web/services/impl/JobDirectoryServerServiceImplSpec.groovy
  genie-web/src/test/java/com/netflix/genie/web/apis/rest/v3/controllers/JobRestControllerTest.java
Labels: Improvement, bug
