Repository Netflix/genie, pull requests merged in 2020-06, with the labels that each got.

#997 Build Improvements
  build.gradle
  genie-agent-app/build.gradle
  genie-agent/build.gradle
  genie-app/build.gradle
  genie-client/build.gradle
  genie-common-external/build.gradle
  genie-common-internal/build.gradle
  genie-common/build.gradle
  genie-proto/build.gradle
  genie-test-web/build.gradle
  genie-test/build.gradle
  genie-ui/build.gradle
  genie-web/build.gradle
Labels: Improvement

#998 Update genie-app docker image
  build.gradle
  genie-app/build.gradle
  genie-app/src/main/docker/Dockerfile
  genie-client/src/integTest/java/com/netflix/genie/client/GenieClientIntegrationTestBase.java
  genie-demo/build.gradle
  genie-ui/build.gradle
Labels: Improvement, feature

#1001 Bug: S3 file not found produces error 500
  genie-common-internal/src/main/java/com/netflix/genie/common/internal/aws/s3/S3ProtocolResolver.java
  genie-common-internal/src/main/java/com/netflix/genie/common/internal/aws/s3/SimpleStorageRangeResource.java
  genie-common-internal/src/test/groovy/com/netflix/genie/common/internal/aws/s3/S3ProtocolResolverSpec.groovy
  genie-common-internal/src/test/groovy/com/netflix/genie/common/internal/aws/s3/SimpleStorageRangeResourceSpec.groovy
  genie-web/src/main/java/com/netflix/genie/web/services/impl/ArchivedJobServiceImpl.java
Labels: bug

#1002 Allow retrieval of arbitrary files via Java client
  genie-client/src/integTest/java/com/netflix/genie/client/JobClientIntegrationTest.java
  genie-client/src/main/java/com/netflix/genie/client/JobClient.java
  genie-client/src/main/java/com/netflix/genie/client/apis/JobService.java
Labels: feature

#1005 Modify client tests to support changes to the server
  genie-client/src/integTest/java/com/netflix/genie/client/ClusterClientIntegrationTest.java
  genie-client/src/integTest/java/com/netflix/genie/client/CommandClientIntegrationTest.java
  genie-client/src/integTest/java/com/netflix/genie/client/JobClientIntegrationTest.java
Labels: Improvement

#1006 Move client integration testing onto more stable docker candidate image
  genie-client/src/integTest/java/com/netflix/genie/client/GenieClientIntegrationTestBase.java
Labels: Improvement

#1015 Improve Demo documentation and compose file
  genie-demo/src/docs/asciidoc/index.adoc
  genie-demo/src/main/docker/docker-compose.yml
Labels: Improvement, documentation
