Repository Netflix/genie, pull requests merged in 2020-01, with the labels that each got.

#934 Bump npm version to avoid vulnerabilities
  genie-ui/package.json
Labels: Improvement, dependencies

#935 Upgrade to Gradle 6 with minimum required versions of plugins
  build.gradle
  codequality/checkstyle/checkstyle.xml
  genie-ui/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#936 Published pom.xml doesn't have proper metadada when using deprecated runtime gradle configuration
  build.gradle
  genie-web/build.gradle
Labels: dependencies

#938 Update client image base image
  genie-demo/src/main/docker/client/Dockerfile
  genie-demo/src/main/docker/client/example/init_demo.py
  genie-demo/src/main/docker/client/example/move_tags.py
  genie-demo/src/main/docker/client/example/reset_tags.py
  genie-demo/src/main/docker/client/example/run_hadoop_job.py
  genie-demo/src/main/docker/client/example/run_hdfs_job.py
  genie-demo/src/main/docker/client/example/run_spark_shell_job.py
  genie-demo/src/main/docker/client/example/run_spark_submit_job.py
  genie-demo/src/main/docker/client/example/run_yarn_job.py
Labels: dependencies

#939 Upgrade to nebula.netflixoss 8.4.3
  build.gradle
Labels: dependencies

#940 Support s3n:// and s3a:// dependency URLs
  genie-common-internal/src/main/java/com/netflix/genie/common/internal/aws/s3/S3ProtocolResolver.java
  genie-common-internal/src/test/groovy/com/netflix/genie/common/internal/aws/s3/S3ProtocolResolverSpec.groovy
Labels: Improvement

#942 Upgrade Asciidoctor plugin to latest stable
  build.gradle
  genie-demo/build.gradle
  genie-docs/build.gradle
  genie-web/build.gradle
Labels: dependencies, documentation

#944 Upgrade nebula netflixoss plugin to increase timeouts for bintray api calls
  build.gradle
Labels: dependencies
