Repository Netflix/genie, pull requests merged in 2021-12, with the labels that each got.

#1126 add jobId in the logs of file transfer related activities, whenever possible
  genie-web/src/main/java/com/netflix/genie/web/agent/apis/rpc/v4/endpoints/GRpcAgentFileStreamServiceImpl.java
Labels: Improvement

#1127 add jobId in the logs of file transfer related activities, whenever possible
  genie-web/src/main/java/com/netflix/genie/web/agent/apis/rpc/v4/endpoints/GRpcAgentFileStreamServiceImpl.java
Labels: Improvement

#1128 Add support for byte ranges to job output requests in java client
  build.gradle
  genie-client/src/integTest/java/com/netflix/genie/client/GenieClientIntegrationTestBase.java
  genie-client/src/integTest/java/com/netflix/genie/client/JobClientIntegrationTest.java
  genie-client/src/main/java/com/netflix/genie/client/JobClient.java
  genie-client/src/main/java/com/netflix/genie/client/apis/JobService.java
Labels: feature

#1129 Add support for byte ranges to job output requests in java client
  build.gradle
  genie-client/src/integTest/java/com/netflix/genie/client/GenieClientIntegrationTestBase.java
  genie-client/src/integTest/java/com/netflix/genie/client/JobClientIntegrationTest.java
  genie-client/src/main/java/com/netflix/genie/client/JobClient.java
  genie-client/src/main/java/com/netflix/genie/client/apis/JobService.java
Labels: feature

#1132 Upgrade dependencies
  gradle.properties
Labels: dependencies

#1133 Upgrade dependencies
  gradle.properties
Labels: dependencies
