Repository Netflix/genie, pull requests merged in 2021-03, with the labels that each got.

#1077 Upgrade nebula.netflixoss to replace bintray publication and update TravisCI secrets
  .gitignore
  .travis.yml
  build.gradle
  secrets/signing-key.enc
  travis/buildViaTravis.sh
Labels: dependencies

#1079 Add command array to available Titus launcher options
  genie-docs/src/docs/asciidoc/_properties.adoc
  genie-web/src/main/java/com/netflix/genie/web/agent/launchers/dtos/TitusBatchJobRequest.java
  genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImpl.java
  genie-web/src/main/java/com/netflix/genie/web/properties/TitusAgentLauncherProperties.java
  genie-web/src/test/groovy/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImplSpec.groovy
  genie-web/src/test/groovy/com/netflix/genie/web/properties/TitusAgentLauncherPropertiesSpec.groovy
Labels: Improvement

#1081 Upgrade to netflixoss 9.2.2 to publish candidates to maven central
  build.gradle
  gradle.properties
Labels: dependencies

#1082 Fix state bug for job group info object
  genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImpl.java
Labels: bug

#1083 Create new instance for attributes and security group to avoid potential race condition in downstream
  genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImpl.java
Labels: bug

#1084 enable debug and build scans for triaging network issues
  build.gradle
  settings.gradle
  travis/buildViaTravis.sh
Labels: dependencies

#1085 buildViaTravis.sh: run with --stacktrace flag
  travis/buildViaTravis.sh
Labels: dependencies

#1089 Add retry logic to Titus API calls
  genie-web/src/main/java/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImpl.java
  genie-web/src/main/java/com/netflix/genie/web/spring/autoconfigure/agent/launchers/AgentLaunchersAutoConfiguration.java
  genie-web/src/test/groovy/com/netflix/genie/web/agent/launchers/impl/TitusAgentLauncherImplSpec.groovy
  genie-web/src/test/java/com/netflix/genie/web/spring/autoconfigure/agent/launchers/AgentLaunchersAutoConfigurationTest.java
Labels: Improvement

#1090 Update dependencies
  README.md
  build.gradle
  genie-app/build.gradle
  genie-docs/src/docs/asciidoc/_properties.adoc
  genie-swagger/build.gradle
  genie-swagger/src/main/java/com/netflix/genie/swagger/spring/autoconfigure/SwaggerAutoConfiguration.java
  genie-swagger/src/main/java/com/netflix/genie/swagger/spring/autoconfigure/package-info.java
  genie-swagger/src/main/resources/META-INF/spring.factories
  genie-swagger/src/test/java/com/netflix/genie/swagger/spring/autoconfigure/SwaggerAutoConfigurationTest.java
  genie-swagger/src/test/java/com/netflix/genie/swagger/spring/autoconfigure/package-info.java
  genie-web/build.gradle
  genie-web/src/main/java/com/netflix/genie/web/properties/SwaggerProperties.java
  genie-web/src/main/resources/META-INF/spring.factories
  genie-web/src/main/resources/genie-web-defaults.yml
  settings.gradle
Labels: dependencies
